[Info]
name = "CI Documentation"
description = "Documentation covering all test jobs and what they are and do"
long_description = """
## Building the documentation

### Prereqs

Ability to create a virtualenv, install `virtualenvwrapper` from the archives.

### Build

```
> mkvirtualenv k8s
> pip install -rrequirements.txt
> pip install -rrequirements_doc.txt
> ogc --spec maintainer-spec.toml --debug execute -t docs && mkdocs serve
```

### Bootstrapping in dev mode

```
juju bootstrap aws/us-east-2 aws-dev --config test-mode=true
juju model-defaults test-mode=true
```
"""

[Info.mkdocs]
destination = "index.md"