[Info]
name = "k8sci spec"
description = "OGC Spec for generating documentation, running unittests, etc."

[SpecDoc]
name = "Docs"
file_glob = "**/*spec.toml"
top_level_dir = "."
tags = ["docs"]

[[Runner]]
name = "Build and serve locally"
run = """
#!/bin/bash

mkdocs serve
"""
tags = ["docs"]

[[Runner]]
name = "Build and publish docs"
run = """
#!/bin/bash

mkdocs build
aws s3 sync site/ s3://jenkaas/docs
"""
tags = ["docs-deploy"]

[[Runner]]
name = "Unittests"
description = "Runs any unittests specific to the functioning of the scripts in ci"
entry_point = ["pytest"]
args = ["builders"]
tags = ["test"]

