[Info]
name = "Validate CK on supported releases"
description = """
Runs validation test suite against a vanilla deployment of Charmed Kubernetes
"""

[Env]
requires = ["JUJU_MODEL",
            "JUJU_CONTROLLER",
            "JUJU_CLOUD",
            "JUJU_DEPLOY_BUNDLE_CHANNEL"]
GIT_SSH_COMMAND = "ssh -i /var/lib/jenkins/.ssh/cdkbot_rsa -oStrictHostKeyChecking=no"

[Juju.bootstrap]
constraints = "arch=amd64"
debug = false
disable_add_model = false

[Juju.deploy]
bundle = "cs:~containers/charmed-kubernetes"
overlay = """
applications:
  kubernetes-master:
    options:
      channel: 1.16/edge
  kubernetes-worker:
    options:
      channel: 1.16/edge
"""
bundle_channel = "edge"
charm_channel = "edge"
wait = true

[[Runner]]
name = "Validating deployment"
run = """
#!/bin/bash
set -eux

pytest integration/validation.py --connection $JUJU_CONTROLLER:$JUJU_MODEL \
                                 --cloud $JUJU_CLOUD \
                                 --bundle-channel $JUJU_DEPLOY_BUNDLE_CHANNEL
"""
deps = ['pip:flaky>=3.6.0,<4',
        'pip:pytest',
        'pip:asyncio_extras',
        'pip:pytest-asyncio',
        'pip:juju',
        'snap:juju/latest/candidate',
        'snap:juju-wait/latest/stable']

[[Runner]]
name = "Tearing down deployment"
run = """
#!/bin/bash
set -eux

juju destroy-controller -y --destroy-all-models --destroy-storage $JUJU_CONTROLLER"
"""