[Info]
name = "Sync upstream components to downstream"
description = """
Keeps upstream components synced with github/charmed-kubernetes
"""

[[Runner]]
name = "Sync upstream components to downstream"
description = """
Handles the syncing of upstream to github/charmed-kubernetes
"""
entry_point = ["python3", "-m", "sync"]
args = ["forks", "--layer-list", "$LAYER_LIST"]
tags = ["sync"]