[Info]
name = "Performs a Kubernetes bugfix release"
description = """
Performs a Kubernetes bugfix release, which includes validation across the base
deployment as well as variations including calico, tigera, vault, nvidia, and
ceph.
"""
long_description = """
# Bugfix Release Process

## Steps

1. Cherry-pick fixes from edge into stable branches
2. Build new charms from those stable branches
3. Promote built bundles/charms into the charmstores beta channel
4. Notify solutions-qa to start their test harness
5. Run validation against 'vanilla' Charmed Kubernetes
6. Run validation against variations
   6a. NVidia
   6b. Tigera EE
   6c. Calico
   6d. Vault
   6e. Ceph
7. Run an upgrade from previous minor release
8. Run validation against that upgrade
9. Document release notes
   9a. Bugfixes
   9b. Enhancements
   9c. Known Limitations/Issues
10. Promote to charmstore stable branches
11. Send announcement to k8s-crew
"""